Wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("new_page", views.new_page, name="new_page"),
    path("<str:title>/edit_page", views.edit_page, name="edit_page"),
    path("<str:title>", views.entry, name="entry")
]

Wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('encyclopedia/', include("encyclopedia.urls"))
]

Wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

Wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms
from . import util
import markdown2
import random

class NewTaskForm(forms.Form):
    wiki_page = forms.CharField(label="Search Encyclopedia")


def index(request):
    if request.GET.get("random") == "true":
        rand_title = random.choice(util.list_entries())
        return redirect("encyclopedia:entry", title=rand_title)
    form = NewTaskForm(request.GET)
    if form.is_bound and form.is_valid():
        query = form.cleaned_data["wiki_page"]
        return redirect("encyclopedia:entry", title=query)

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": NewTaskForm(),
    })

def entry(request, title):
    contents = util.get_entry(title)
    if contents is None:
        results = [entry for entry in util.list_entries() if title in entry]
        if len(results) != 0:
            return render(request, "encyclopedia/search.html", {
                "results": results,
                "title": title
            })
        return render(request, "encyclopedia/error.html", {
                "error_message": f'"{title.strip()}" does not exist.'
            })

    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "contents": markdown2.markdown(contents.strip()),
    })

def new_page(request):
    if request.method == "POST":
        title = request.POST.get("title")
        if title in util.list_entries():
            return render(request, "encyclopedia/error.html", {
                "error_message": f'"{title.strip()}" already exists.'
            })
        content = request.POST.get("content")
        util.save_entry(title, content)
        return redirect("encyclopedia:entry", title=title)
    return render(request, "encyclopedia/new_page.html")

def edit_page(request, title):
    if request.method == "POST":
        new_content = request.POST.get("new_content")
        util.save_entry(title, new_content)
        return redirect("encyclopedia:entry", title=title)

    if title not in util.list_entries():
        return render(request, "encyclopedia/error.html", {
                "error_message": f'"{title.strip()}" does not exist.'
            })
    return render(request, "encyclopedia/edit_page.html", {
        "title": title,
        "content": util.get_entry(title)
    })

Wiki/encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}


{% block body %}

<form action="{% url 'encyclopedia:edit_page' title=title %}" method="post">
    {% csrf_token %}
    <textarea name="new_content">{{ content }}</textarea>
    <input type="submit" value="Submit">
</form>

{% endblock %}

Wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block body %}

{{ contents|safe }}
<a href="{% url 'encyclopedia:edit_page' title=title %}">Edit Content</a>

{% endblock %}

Wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}



{% block body %}

        <h1>{{ error_message }}</h1>

{% endblock %}

Wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block nav %}
    <h3>All Pages</h3>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

Wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="get">
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:index' %}?random=true">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

Wiki/encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}


{% block body %}

<form action="{% url 'encyclopedia:new_page' %}" method="post">
    {% csrf_token %}
    <input type="text" placeholder="Title" name="title">
    <textarea placeholder="Content" name="content"></textarea>
    <input type="submit" value="Submit">
</form>

{% endblock %}

Wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}


{% block body %}

<h2>Closest Results to "{{ title }}":</h2>
<ul>
    {% for result in results %}
    <li><a href="{% url 'encyclopedia:entry' result %}">{{ result }}</a></li>
    {% endfor %}
</ul>

{% endblock %}